# Generated by Django 2.1.4 on 2019-08-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_meals_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
